version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: revcart-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: revcart
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: revcart-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    image: amanpardeshi01/revcart-backend:latest
    container_name: revcart-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/revcart?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/revcart_logs"
      REVCART_SECURITY_JWT_SECRET: "ChangeMeToAStrongSecretKeyForRevCartBackend123456"
      REVCART_SECURITY_JWT_EXPIRATION_MS: "86400000"
    networks:
      default:
        aliases:
          - backend
    depends_on:
      - mysql
      - mongodb
    restart: unless-stopped

  frontend:
    image: amanpardeshi01/revcart-frontend:latest
    container_name: revcart-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
  mongo_data:
